# Generated by Django 3.2.5 on 2022-05-13 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_auto_20220428_0658'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='dislikes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='likes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
