# Generated by Django 3.2.5 on 2022-05-13 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_auto_20220513_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='dislikes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='movie',
            name='likes',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
