# Generated by Django 3.2.5 on 2022-05-17 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_movie_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='user',
        ),
    ]
