# Generated by Django 3.2.5 on 2022-05-18 16:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0016_movie_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='users',
        ),
        migrations.AddField(
            model_name='movie',
            name='usersDisiked',
            field=models.ManyToManyField(related_name='users_disliked_movie', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movie',
            name='usersLiked',
            field=models.ManyToManyField(related_name='users_liked_movie', to=settings.AUTH_USER_MODEL),
        ),
    ]
